export var labels = {
    "ship": "Schip",
    "environment": "Milieu",
    "manAndBeast": "Mens en dier",
    "fireExplosion": "Brand / explosie",
    "threat": "Dreiging",
    "remaining": "Overig",
    "collision": "Aanvaring",
    "blackout": "Blackout",
    "cableAnchor": "Tros / Anker",
    "pgsNearMiss": "PGS / Near miss",
    "incidentShip": "Incident schip",
    "mainEngine": "Hoofdmotor",
    "auxiliaryEngine": "Hulpbedrijf",
    "steeringEquipment": "Stuurgerei",
    "waterPollution": "Waterverontreiniging",
    "soilContamination": "Bodem verontreiniging",
    "airPollution": "Lucht verontreiniging",
    "medicalAssistance": "Medische bijstand",
    "manOverboard": "Drenkeling",
    "marineMammal": "Zeezoogdier",
    "fire": "Brand",
    "cargoScalding": "Ladingbroei",
    "explosionHazard": "Explosiegevaar",
    "harborActions": "Acties in de haven",
    "threatTerror": "Dreiging / Terreur",
    "portHealth": "Port Health",
    "bridgesLocksWeir": "Bruggen/Sluizen/Waterkering",
    "communicationFailure": "Uitval communicatie",
    "publicUtilitiesFailure": "Uitval nutsdiensten",
    "conduitCollection": "Leidingstraat",
    "railIncident": "Spoorincident",
    "roadAccident": "Wegongval",
    "aviationAccident": "Luchtvaartongeval",
    "employeeAccident": "Ongeval eigen personeel",
};

